In [1]:
import tensorflow as tf

input_x = tf.constant([
    [[[5, 6, 0, 1, 8, 2],
      [2, 5, 7, 2, 3, 7],
      [0, 7, 2, 4, 5, 6],
      [5, 3, 6, 9, 3, 1],
      [6, 5, 3, 1, 4, 6],
      [5, 2, 4, 0, 8, 7]

      ]]])
filters = tf.constant([
    [[[-1, 2, -1], 
      [1, 5, 1], 
      [-1, 0, -1]]]
])

input_x=tf.reshape(input_x,(1,6,6,1))

filters=tf.reshape(filters,(3,3,1,1))

res = tf.nn.conv2d(input_x, filters, strides=1, padding='VALID')
print('Valid 无激活函数下的输出',res)
res=tf.squeeze(res)
print('Valid 条件下ReLU可视化的输出：',res)
res1 = tf.nn.conv2d(input_x, filters, strides=1, padding='SAME')
print('Same 条件下ReLU可视化的输出：',tf.squeeze(res1))
# print('Valid 激活函数下输出',tf.nn.relu(res))

Valid 无激活函数下的输出 tf.Tensor(
[[[[39]
   [24]
   [ 7]
   [27]]

  [[27]
   [16]
   [12]
   [22]]

  [[29]
   [29]
   [48]
   [18]]

  [[20]
   [19]
   [ 9]
   [16]]]], shape=(1, 4, 4, 1), dtype=int32)
Valid 条件下ReLU可视化的输出： tf.Tensor(
[[39 24  7 27]
 [27 16 12 22]
 [29 29 48 18]
 [20 19  9 16]], shape=(4, 4), dtype=int32)
Same 条件下ReLU可视化的输出： tf.Tensor(
[[26 26  0  3 34 15]
 [12 39 24  7 27 29]
 [ 3 27 16 12 22 43]
 [16 29 29 48 18 11]
 [40 20 19  9 16 25]
 [34 20 22  7 48 51]], shape=(6, 6), dtype=int32)


In [2]:
criterion = nn.BCELoss()#默认是求均值，数据需要是浮点型数据
pre=torch.tensor([0.2,0.8,0.4,0.1,0.9]).float()
tar=torch.tensor([0,1,0,0,1]).float()
l=criterion(pre,tar)
l

tensor(0.2336)

In [14]:
pre=torch.tensor([2,3,5]).float()
prob = torch.nn.functional.softmax(pre, dim=0)
prob

tensor([0.0420, 0.1142, 0.8438])